services:
  mongo:
    image: mongo:latest
    command: mongod --replSet rs0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
